# Generated by Django 3.1 on 2020-08-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0002_auto_20200826_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.FloatField(null=True),
        ),
    ]
