# Generated by Django 3.1 on 2020-08-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0004_auto_20200826_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='cost',
        ),
        migrations.AddField(
            model_name='sku',
            name='avg_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
