# Generated by Django 3.1 on 2020-09-07 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sku', '0009_auto_20200907_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='stock',
        ),
        migrations.AddField(
            model_name='marketplace',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
