# Generated by Django 3.1 on 2020-09-07 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0011_marketplace_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
