# Generated by Django 3.1 on 2020-09-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0013_auto_20200907_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku',
            old_name='code',
            new_name='slug',
        ),
    ]
