# Generated by Django 3.1 on 2020-09-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0015_auto_20200907_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
