# Generated by Django 3.1 on 2020-09-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0016_auto_20200907_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
