# Generated by Django 3.1 on 2020-09-08 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0018_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplace',
            name='code',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='code',
        ),
    ]
