# Generated by Django 3.1 on 2020-09-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0019_auto_20200908_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
